WITH ADD_DAUKY AS
(
	SELECT *,ROW_NUMBER() OVER (PARTITION BY CASA_ACCOUNT, DATEPART(MONTH,TRANS_TIME) ORDER BY TRANS_TIME) AS STT
	FROM CASA
	WHERE TRANS_TIME <= '2024-03-31 23:59:59'
)
-- SỐ DƯ ĐẦU KỲ
SELECT DATEPART(MONTH,TRANS_TIME) 'THÁNG',
	   SUM(PRE_AMOUNT)			  'SỐ DƯ ĐẦU KỲ'
FROM ADD_DAUKY
WHERE STT = 1 
GROUP BY DATEPART(MONTH,TRANS_TIME)
ORDER BY [THÁNG]


--TỔNG SỐ TIỀN CHUYỂN KHOẢN TRONG NGÂN HÀNG TỚI CÁC NGÂN HÀNG KHÁC
SELECT DATEPART(MONTH,TRANS_TIME)	'THÁNG',
	   SUM(DECREASE)				'TỔNG TIỀN CHUYỂN KHOẢN'
FROM CASA
WHERE TRANSFER_TYPE_CODE = 'out' AND INCREASE = 0
GROUP BY DATEPART(MONTH,TRANS_TIME)
ORDER BY [THÁNG]


--TỔNG SỐ TIỀN NHẬN CHUYỂN KHOẢN TỪ CÁC NGÂN HÀNG KHÁC
SELECT DATEPART(MONTH,TRANS_TIME)	'THÁNG',
	   SUM(INCREASE)				'TỔNG TIỀN NHẬN CHUYỂN KHOẢN'
FROM CASA
WHERE  TRANSFER_TYPE_CODE = 'out' AND DECREASE = 0
GROUP BY DATEPART(MONTH,TRANS_TIME)
ORDER BY [THÁNG]


--TỔNG SỐ TIỀN MẶT NỘP RÚT RA TỪ TÀI KHOẢN
SELECT DATEPART(MONTH, TRANS_TIME) 'THÁNG',
		SUM(CASE WHEN NOTE = 'RUT TIEN MAT' THEN DECREASE ELSE 0 END) AS 'TONG TIEN RUT',
		SUM(CASE WHEN NOTE = 'NOP TIEN MAT' THEN INCREASE ELSE 0 END) AS 'TONG TIEN NOP'
FROM CASA
GROUP BY DATEPART(MONTH, TRANS_TIME)
ORDER BY [THÁNG]


--- SỐ DƯ CUỐI KỲ
WITH ADD_CUOIKY AS
(
	SELECT *,ROW_NUMBER() OVER (PARTITION BY CASA_ACCOUNT, DATEPART(MONTH,TRANS_TIME) ORDER BY TRANS_TIME DESC) AS STT
	FROM CASA
	WHERE TRANS_TIME <= '2024-03-31 23:59:59'
)
SELECT DATEPART(MONTH,TRANS_TIME) 'THÁNG',
	   SUM(AFTER_AMOUNT)		  'SỐ DƯ CUỐI KỲ'
FROM ADD_CUOIKY
WHERE STT = 1 
GROUP BY DATEPART(MONTH,TRANS_TIME)
ORDER BY [THÁNG]


--TOP 3 KHÁCH HÀNG CÓ TỔNG LƯỢNG TIỀN GIAO DỊCH 
SELECT *
FROM (
    SELECT C.CUSTID                            AS 'MA_KH',
           CB.BRANCH_NAME                      AS 'TEN_CHI_NHANH',
           C.CUSTNAME                          AS 'TEN_KH',
           CA.CASA_ACCOUNT                     AS 'TK CASA',
           SUM(INCREASE) + SUM(DECREASE)       AS 'TONG TIEN GIAO DICH',
           DENSE_RANK() OVER (ORDER BY (SUM(INCREASE) + SUM(DECREASE)) DESC) AS STT
    FROM CASA CA
    JOIN CUSTOMER C       ON CA.CASA_ACCOUNT = C.CASA_ACCOUNT
    JOIN CODE_BRANCH CB   ON C.BRANCH_CODE = CB.BRANCH_CODE
    GROUP BY C.CUSTID,
             CB.BRANCH_NAME,
             C.CUSTNAME,
             CA.CASA_ACCOUNT
) AS Subquery
WHERE STT <= 3
ORDER BY [TONG TIEN GIAO DICH] DESC;


SỬA BÀI
SELECT		A.CASA_ACCOUNT															'TÀI KHOẢN CASA',
			C.BRANCH_CODE															'MÃ CHI NHÁNH',
			C.BRANCH_NAME															'CHI NHÁNH',
			B.CUSTID																'MÃ KHÁCH HÀNG',
			B.CUSTNAME																'TÊN KHÁCH HÀNG',
			SUM(A.INCREASE) + SUM(A.DECREASE)										'TỔNG TIỀN',
			DENSE_RANK() OVER(ORDER BY (SUM(A.INCREASE) + SUM(A.DECREASE)) DESC)	'XẾP HẠNG'
FROM		CASA			AS A
FULL JOIN	CUSTOMER		AS B	ON A.CASA_ACCOUNT = B.CASA_ACCOUNT
FULL JOIN	CODE_BRANCH		AS C	ON B.BRANCH_CODE = C.BRANCH_CODE
WHERE		A.CASA_ACCOUNT IS NOT NULL
GROUP BY	A.CASA_ACCOUNT, B.CUSTID, B.CUSTNAME, C.BRANCH_CODE, C.BRANCH_NAME
