---------------------------------------BÁO CÁO TIẾT KIỆM----------------------------------
---- VỀ QUY MÔ
CREATE VIEW TONGHOP_KT AS
(
	SELECT *
	FROM 
		(SELECT SAVING_ACC_ID	'MATK_DK',
			   CUSTID			'MAKH_DK',
			   SAV_AMOUNT		'TIENTK_DK'
		FROM SAVING_ACCOUNT 
		WHERE SAVE_DATE <= '2023-12-31' and SAVE_END_DATE > '2023-12-31') DAUKY 
	FULL OUTER JOIN	
		(SELECT SAVING_ACC_ID	'MATK_PST1',
			   CUSTID			'MAKH_PST1',
			   SAV_AMOUNT		'TIENTK_PST1'
		FROM SAVING_ACCOUNT 
		WHERE SAVE_DATE >'2023-12-31' and SAVE_DATE <= '2024-03-31') PST_QUY1
	ON DAUKY.MATK_DK = PST_QUY1.MATK_PST1
	FULL OUTER JOIN
		(SELECT SAVING_ACC_ID	'MATK_PST2',
			   CUSTID			'MAKH_PST2',
			   SAV_AMOUNT		'TIENTK_PST2'
		FROM SAVING_ACCOUNT 
		WHERE SAVE_DATE >'2024-03-31' and SAVE_DATE <= '2024-06-30') PST_QUY2
	ON DAUKY.MATK_DK = PST_QUY2.MATK_PST2 
	LEFT JOIN
		(SELECT SAVING_ACC_ID	'MATK_PSG1',
			   CUSTID			'MAKH_PSG1',
			   SAV_AMOUNT		'TIENTK_PSG1'
		FROM SAVING_ACCOUNT 
		WHERE SAVE_END_DATE >'2023-12-31' and SAVE_END_DATE <= '2024-03-31') PSG_QUY1
	ON DAUKY.MATK_DK = PSG_QUY1.MATK_PSG1 
	OR PST_QUY1.MATK_PST1 = PSG_QUY1.MATK_PSG1
	LEFT JOIN
		(SELECT SAVING_ACC_ID	'MATK_PSG2',
			   CUSTID			'MAKH_PSG2',
			   SAV_AMOUNT		'TIENTK_PSG2'
		FROM SAVING_ACCOUNT 
		WHERE SAVE_END_DATE >'2024-03-31' and SAVE_END_DATE <= '2024-06-30') PSG_QUY2
	ON DAUKY.MATK_DK = PSG_QUY2.MATK_PSG2 
	OR PST_QUY2.MATK_PST2 = PSG_QUY2.MATK_PSG2
	LEFT JOIN 
		(SELECT SAVING_ACC_ID	'MATK_CK',
			   CUSTID			'MAKH_CK',
			   SAV_AMOUNT		'TIENTK_CK'
		FROM SAVING_ACCOUNT 
		WHERE SAVE_DATE <='2024-06-30' and SAVE_END_DATE > '2024-06-30') CUOIKY
	ON DAUKY.MATK_DK = CUOIKY.MATK_CK OR
	   PST_QUY1.MATK_PST1 = CUOIKY.MATK_CK OR
	   PST_QUY2.MATK_PST2 = CUOIKY.MATK_CK
)
--- SỐ TÀI KHOẢN , SỐ LƯỢNG KHÁCH HÀNG, TỔNG SỐ TIỀN ĐẦU KỲ
SELECT  COUNT(MATK_DK)				'SỐ TK ĐẦU KỲ', 
		COUNT(DISTINCT MAKH_DK)		'SỐ KH ĐẦU KỲ', 
		SUM(TIENTK_DK)				'SÔ TIỀN TK ĐẦU KỲ'
FROM TONGHOP_KT
--- SỐ TÀI KHOẢN , SỐ LƯỢNG KHÁCH HÀNG, TỔNG SỐ TIỀN QUÝ 1
SELECT  COUNT(MATK_PST1)				'SỐ TK PST QUÝ 1', 
		SUM(TIENTK_PST1)				'SÔ TIỀN TK PST QUÝ 1'
FROM TONGHOP_KT

SELECT COUNT(DISTINCT MAKH_PST1) 'SỐ KH PST QUÝ 1'
FROM TONGHOP_KT
WHERE MAKH_PST1 NOT IN (SELECT DISTINCT MAKH_DK FROM TONGHOP_KT WHERE MAKH_DK IS NOT NULL ) AND MAKH_PST1 IS NOT NULL

--- SỐ TÀI KHOẢN , SỐ LƯỢNG KHÁCH HÀNG, TỔNG SỐ TIỀN QUÝ 2
SELECT  COUNT(MATK_PST2)				'SỐ TK PST QUÝ 2', 
		SUM(TIENTK_PST2)				'SÔ TIỀN TK PST QUÝ 2'
FROM TONGHOP_KT

SELECT COUNT(DISTINCT MAKH_PST2) 'SỐ KH PST QUÝ 2'
FROM TONGHOP_KT
WHERE MAKH_PST2 NOT IN (SELECT DISTINCT MAKH_DK FROM TONGHOP_KT WHERE MAKH_DK IS NOT NULL ) 
	  AND MAKH_PST2 IS NOT NULL
	  AND MAKH_PST2 NOT IN (SELECT DISTINCT MAKH_PST1 FROM TONGHOP_KT WHERE MAKH_PST1 IS NOT NULL ) 

--- SỐ TÀI KHOẢN , SỐ LƯỢNG KHÁCH HÀNG, TỔNG SỐ TIỀN PHÁT SINH GIẢM QUÝ 1
SELECT  COUNT(MATK_PSG1)				'SỐ TK PSG QUÝ 1', 
		SUM(TIENTK_PSG1)				'SÔ TIỀN TK PSG QUÝ 1'
FROM TONGHOP_KT

SELECT COUNT(DISTINCT MAKH_PSG1) 'SỐ KH PSG QUÝ 1'
FROM TONGHOP_KT
WHERE MAKH_PSG1 NOT IN (SELECT DISTINCT MAKH_CK FROM TONGHOP_KT WHERE MAKH_CK IS NOT NULL ) AND MAKH_PSG1 IS NOT NULL

--- SỐ TÀI KHOẢN , SỐ LƯỢNG KHÁCH HÀNG, TỔNG SỐ TIỀN PHÁT SINH GIẢM QUÝ 2
SELECT  COUNT(MATK_PSG2)				'SỐ TK PSG QUÝ 2', 
		SUM(TIENTK_PSG2)				'SÔ TIỀN TK PSG QUÝ 2'
FROM TONGHOP_KT

SELECT COUNT(DISTINCT MAKH_PSG2) 'SỐ KH PSG QUÝ 2'
FROM TONGHOP_KT
WHERE MAKH_PSG2 NOT IN (SELECT DISTINCT MAKH_CK FROM TONGHOP_KT WHERE MAKH_CK IS NOT NULL ) AND MAKH_PSG2 IS NOT NULL

--- SỐ TÀI KHOẢN , SỐ LƯỢNG KHÁCH HÀNG, TỔNG SỐ TIỀN CUỐI KỲ
SELECT  COUNT(MATK_CK)				'SỐ TK ĐẦU KỲ', 
		COUNT(DISTINCT MAKH_CK)		'SỐ KH ĐẦU KỲ', 
		SUM(TIENTK_CK)				'SÔ TIỀN TK ĐẦU KỲ'
FROM TONGHOP_KT

-------------------------------------------CÁC KHOẢN TẤT TOÁN NĂM 2024-----------------------
-- SỐ TIỀN GỐC PHẢI TRẢ
SELECT 
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 1 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) 'TIEN GOC TAT TOAN QUY 1',
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 2 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) 'TIEN GOC TAT TOAN QUY 2',
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 3 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) 'TIEN GOC TAT TOAN QUY 3',
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 4 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) 'TIEN GOC TAT TOAN QUY 4',
	SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-1-1','2024-3-31')*INTEREST/365/100) 'LÃI QUÝ 1',
	SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-4-1','2024-6-30')*INTEREST/365/100) 'LÃI QUÝ 2',
	SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-7-1','2024-9-30')*INTEREST/365/100) 'LÃI QUÝ 3',
	SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-10-1','2024-12-31')*INTEREST/365/100) 'LÃI QUÝ 4',
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 1 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) + SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-1-1','2024-3-31')*INTEREST/365/100) 'TONG TIEN TAT TOAN QUY 1',
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 2 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) + SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-4-1','2024-6-30')*INTEREST/365/100) 'TONG TIEN TAT TOAN QUY 2',
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 3 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) + SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-7-1','2024-9-30')*INTEREST/365/100) 'TONG TIEN TAT TOAN QUY 3',
	SUM(CASE WHEN (DATEPART(QUARTER, SAVE_END_DATE) = 4 AND YEAR(SAVE_END_DATE) = 2024) THEN SAV_AMOUNT ELSE 0 END) + SUM([SAV_AMOUNT] * DATEDIFF(DAY,'2024-10-1','2024-12-31')*INTEREST/365/100) 'TONG TIEN TAT TOAN QUY 4'
FROM SAVING_ACCOUNT
WHERE SAVE_END_DATE >= '2024-01-01'
----------------------------------------PHÂN LOẠI THEO CÁC TIÊU CHÍ ------------------------
WITH PHANLOAI AS
(
	SELECT SAVING_ACC_ID,SAV_AMOUNT,
		CASE
			WHEN SAV_AMOUNT < 1000000000 THEN 'DUOI 1 TY'
			WHEN SAV_AMOUNT BETWEEN 1000000000 AND 9999999999 THEN 'TU 1 DEN 10 TY'
			WHEN SAV_AMOUNT BETWEEN 10000000000 AND 49999999999 THEN 'TU 10 TY DEN 50 TY'
		ELSE 'TREN 50 TY'
		END AS PHANLOAI_TKTK
	FROM SAVING_ACCOUNT
)
SELECT PHANLOAI_TKTK		'PHAN LOAI',
	   COUNT(SAVING_ACC_ID) 'SỐ TÀI KHOẢN',
	   SUM(SAV_AMOUNT)      'TỔNG SỐ TIỀN'
FROM PHANLOAI
GROUP BY PHANLOAI_TKTK