WITH TONGHOP AS
(
	SELECT *
	FROM
		(SELECT DEBID		'HDTD_DK',
			   CUSTID		'MAKH_DK',
			   CR_AMOUNT	'TIENVAY_DK'
		FROM CREDIT_CONTRACT
		WHERE CR_CONTRACT_DATE <= '2023-12-31' AND CR_CONTRACT_END_DATE > '2023-12-31') DAUKY

		FULL OUTER JOIN 

		(SELECT DEBID		'HDTD_PST1',
			   CUSTID		'MAKH_PST1',
			   CR_AMOUNT	'TIENVAY_PST1'
		FROM CREDIT_CONTRACT
		WHERE CR_CONTRACT_DATE > '2023-12-31' AND CR_CONTRACT_DATE <= '2024-03-31') PST1 ON DAUKY.HDTD_DK = PST1.HDTD_PST1

		FULL OUTER JOIN 

		(SELECT DEBID		'HDTD_PST2',
			   CUSTID		'MAKH_PST2',
			   CR_AMOUNT	'TIENVAY_PST2'
		FROM CREDIT_CONTRACT
		WHERE CR_CONTRACT_DATE > '2024-03-31' AND CR_CONTRACT_DATE <= '2024-06-30') PST2 ON DAUKY.HDTD_DK = PST2.HDTD_PST2

		LEFT JOIN

		(SELECT DEBID		'HDTD_PSG1',
			   CUSTID		'MAKH_PSG1',
			   CR_AMOUNT	'TIENVAY_PSG1'
		FROM CREDIT_CONTRACT
		WHERE CR_CONTRACT_END_DATE > '2023-12-31' AND CR_CONTRACT_END_DATE <= '2024-03-31') PSG1 ON DAUKY.HDTD_DK = PSG1.HDTD_PSG1
																								OR PST1.HDTD_PST1 = PSG1.HDTD_PSG1

		LEFT JOIN

		(SELECT DEBID		'HDTD_PSG2',
			   CUSTID		'MAKH_PSG2',
			   CR_AMOUNT	'TIENVAY_PSG2'
		FROM CREDIT_CONTRACT
		WHERE CR_CONTRACT_END_DATE > '2024-03-31' AND CR_CONTRACT_END_DATE <= '2024-06-30') PSG2 ON DAUKY.HDTD_DK = PSG2.HDTD_PSG2
																								OR PST2.HDTD_PST2 = PSG2.HDTD_PSG2

		LEFT JOIN

		(SELECT DEBID		'HDTD_CK',
			   CUSTID		'MAKH_CK',
			   CR_AMOUNT	'TIENVAY_CK'
		FROM CREDIT_CONTRACT
		WHERE CR_CONTRACT_DATE <= '2024-06-30' AND CR_CONTRACT_END_DATE > '2024-06-30') CUOIKY ON DAUKY.HDTD_DK = CUOIKY.HDTD_CK
																							   OR PST1.HDTD_PST1 = CUOIKY.HDTD_CK
																							   OR PST2.HDTD_PST2 = CUOIKY.HDTD_CK
)
-- ĐÂU KỲ 
--SELECT COUNT(HDTD_DK)	'SỐ HDTD ĐÂU KỲ',
--	   COUNT(DISTINCT MAKH_DK) 'SỐ KH ĐẦU KỲ',
--	   SUM(TIENVAY_DK)  'SỐ TIỀN VAY ĐẦU KỲ',
--	   SUM(TIENVAY_DK) - SUM(ISNULL(B.[THUHOINO],0)) AS 'DƯ NỢ ĐẦU KỲ'
--FROM TONGHOP A 
--				LEFT JOIN (SELECT DEBID, SUM(PRINCIPAL_AMOUNT) 'THUHOINO'
--							FROM DEB_COLLECTION
--							WHERE COLLECT_DATE <= '2023-12-31'
--							GROUP BY DEBID) B ON A.HDTD_DK = B.DEBID

-- PST QUÝ 1
--SELECT COUNT(HDTD_PST1)	'SỐ HDTD PST QUÝ 1',
--	   SUM(TIENVAY_PST1)  'SỐ TIỀN VAY PST QUÝ 1',
--	   SUM(TIENVAY_PST1)  'DƯ NỢ PST QUÝ 1'
--FROM TONGHOP A 
--WHERE MAKH_PST1 IS NOT NULL

--SELECT  COUNT(DISTINCT MAKH_PST1) 'SỐ KH PST QUÝ 1'
--FROM TONGHOP
--WHERE MAKH_PST1 IS NOT NULL AND MAKH_PST1 NOT IN (SELECT MAKH_DK FROM TONGHOP WHERE MAKH_DK IS NOT NULL)

-- PST QUÝ 2
--SELECT COUNT(HDTD_PST2)	'SỐ HDTD PST QUÝ 2',
--	   SUM(TIENVAY_PST2)  'SỐ TIỀN VAY PST QUÝ 2',
--	   SUM(TIENVAY_PST2)  'DƯ NỢ PST QUÝ 2'
--FROM TONGHOP A 
--WHERE MAKH_PST2 IS NOT NULL
				
--SELECT	COUNT(DISTINCT MAKH_PST2) 'SỐ KH PST QUÝ 2'
--FROM TONGHOP A 
--WHERE MAKH_PST2 IS NOT NULL AND MAKH_PST2 NOT IN (SELECT MAKH_DK FROM TONGHOP WHERE MAKH_DK IS NOT NULL)
--							AND MAKH_PST2 NOT IN (SELECT MAKH_PST1 FROM TONGHOP WHERE MAKH_PST1 IS NOT NULL)

-- PSG QUÝ 1
--SELECT COUNT(HDTD_PSG1)	'SỐ HDTD PSG QUÝ 1',
--	   SUM(TIENVAY_PSG1)  'SỐ TIỀN VAY PSG QUÝ 1'
--FROM TONGHOP A 
--WHERE MAKH_PSG1 IS NOT NULL

--SELECT  COUNT(DISTINCT MAKH_PSG1) 'SỐ KH PSG QUÝ 1'
--FROM TONGHOP
--WHERE MAKH_PSG1 IS NOT NULL AND MAKH_PSG1 NOT IN (SELECT MAKH_CK FROM TONGHOP WHERE MAKH_CK IS NOT NULL)

--SELECT SUM(PRINCIPAL_AMOUNT) 'DU NO GOC PSG QUY 1'
--FROM DEB_COLLECTION
--WHERE COLLECT_DATE BETWEEN '2024-01-01' AND '2024-03-31'


-- PSG QUÝ 2
--SELECT COUNT(HDTD_PSG2)	'SỐ HDTD PSG QUÝ 2',
--	   SUM(TIENVAY_PSG2)  'SỐ TIỀN VAY PSG QUÝ 2'
--FROM TONGHOP A 
--WHERE MAKH_PSG2 IS NOT NULL

--SELECT  COUNT(DISTINCT MAKH_PSG2) 'SỐ KH PSG QUÝ 2'
--FROM TONGHOP
--WHERE MAKH_PSG2 IS NOT NULL AND MAKH_PSG2 NOT IN (SELECT MAKH_CK FROM TONGHOP WHERE MAKH_CK IS NOT NULL)

--SELECT SUM(PRINCIPAL_AMOUNT) 'DU NO GOC PSG QUY 2'
--FROM DEB_COLLECTION
--WHERE COLLECT_DATE BETWEEN '2024-04-01' AND '2024-06-30'

--CUỐI KỲ 
SELECT COUNT(HDTD_CK)	'SỐ HDTD CUỐI KỲ',
	   COUNT(DISTINCT MAKH_CK) 'SỐ KH CUỐI KỲ',
	   SUM(TIENVAY_CK)  'SỐ TIỀN VAY CUỐI KỲ',
	   SUM(TIENVAY_CK) - SUM(ISNULL(B.[THUHOINO],0)) AS 'DƯ NỢ CUỐI KỲ'
FROM TONGHOP A 
				LEFT JOIN (SELECT DEBID, SUM(PRINCIPAL_AMOUNT) 'THUHOINO'
							FROM DEB_COLLECTION
							WHERE COLLECT_DATE <= '2024-06-30'
							GROUP BY DEBID) B ON A.HDTD_CK = B.DEBID


---------------------------------TĂNG TRƯỞNG QUA CÁC NĂM---------------------------

SELECT SUM(CASE WHEN (CR_CONTRACT_DATE <= '2021-12-31' AND CR_CONTRACT_END_DATE > '2021-12-31') THEN CR_AMOUNT ELSE 0 END) 'TIỀN VAY 31/12/2021',
		SUM(CASE WHEN (CR_CONTRACT_DATE <= '2022-12-31' AND CR_CONTRACT_END_DATE > '2022-12-31') THEN CR_AMOUNT ELSE 0 END) 'TIỀN VAY 31/12/2022',
		SUM(CASE WHEN (CR_CONTRACT_DATE <= '2023-12-31' AND CR_CONTRACT_END_DATE > '2023-12-31') THEN CR_AMOUNT ELSE 0 END) 'TIỀN VAY 31/12/2023',
		SUM(CASE WHEN (CR_CONTRACT_DATE <= '2022-12-31' AND CR_CONTRACT_END_DATE > '2022-12-31') THEN CR_AMOUNT ELSE 0 END) / SUM(CASE WHEN (CR_CONTRACT_DATE <= '2021-12-31' AND CR_CONTRACT_END_DATE > '2021-12-31') THEN CR_AMOUNT ELSE 0 END) 'TĂNG TRƯỞNG TIỀN VAY 2021-2022',
		SUM(CASE WHEN (CR_CONTRACT_DATE <= '2023-12-31' AND CR_CONTRACT_END_DATE > '2023-12-31') THEN CR_AMOUNT ELSE 0 END) / SUM(CASE WHEN (CR_CONTRACT_DATE <= '2022-12-31' AND CR_CONTRACT_END_DATE > '2022-12-31') THEN CR_AMOUNT ELSE 0 END) 'TĂNG TRƯỞNG TIỀN VAY 2022-2023'
FROM CREDIT_CONTRACT

WITH TAISANDAMBAO AS (
	SELECT DEBID				'MA KHOAN VAY', 
		   CC.MA_ID				'MA HDDB',
		   CR_AMOUNT			'TIEN VAY',
		   CR_CONTRACT_DATE		'NGAY VAY',
		   CR_CONTRACT_END_DATE	'NGAY KET THUC',
		   MB.MA				'MA HDDB-TSDB',
		   MB.THECHAP			'TONG TAI SAN DAM BAO',
		   ROW_NUMBER() OVER(PARTITION BY CC.MA_ID ORDER BY CR_CONTRACT_DATE) as 'STT'
	FROM CREDIT_CONTRACT CC JOIN (SELECT MA.MA_ID 'MA', SUM([COL_AMOUNT]) 'THECHAP'
									FROM [MORTGAGE_AGREEMENT] MA JOIN COLLATERALS C ON MA.MA_ID = C.MA_ID
									GROUP BY MA.MA_ID) AS MB ON MB.MA = CC.MA_ID)

SELECT SUM(CASE WHEN ([NGAY VAY] <= '2021-12-31' AND [NGAY KET THUC] > '2021-12-31') THEN [TONG TAI SAN DAM BAO] ELSE 0 END) 'GIÁ TRỊ TSBĐ 31/12/2021',
		SUM(CASE WHEN ([NGAY VAY] <= '2022-12-31' AND [NGAY KET THUC] > '2022-12-31') THEN [TONG TAI SAN DAM BAO] ELSE 0 END) 'GIÁ TRỊ TSBĐ 31/12/2022',
		SUM(CASE WHEN ([NGAY VAY] <= '2023-12-31' AND [NGAY KET THUC] > '2023-12-31') THEN [TONG TAI SAN DAM BAO] ELSE 0 END) 'GIÁ TRỊ TSBĐ 31/12/2023',
		SUM(CASE WHEN ([NGAY VAY] <= '2022-12-31' AND [NGAY KET THUC] > '2022-12-31') THEN [TONG TAI SAN DAM BAO] ELSE 0 END) / SUM(CASE WHEN ([NGAY VAY] <= '2021-12-31' AND [NGAY KET THUC] > '2021-12-31') THEN [TONG TAI SAN DAM BAO] ELSE 0 END) 'TĂNG TRƯỞNG GIÁ TRỊ TSBĐ 2021-2022',
		SUM(CASE WHEN ([NGAY VAY] <= '2023-12-31' AND [NGAY KET THUC] > '2023-12-31') THEN [TONG TAI SAN DAM BAO] ELSE 0 END) / SUM(CASE WHEN ([NGAY VAY] <= '2022-12-31' AND [NGAY KET THUC] > '2022-12-31') THEN [TONG TAI SAN DAM BAO] ELSE 0 END) 'TĂNG TRƯỞNG GIÁ TRỊ TSBĐ 2022-2023'
FROM TAISANDAMBAO
WHERE STT = 1











SỬA BÀI
SELECT			C.NĂM,
				SUM(C.CR_AMOUNT)																															'TỔNG GIÁ TRỊ HĐTD',
				LAG(SUM(C.CR_AMOUNT), 1) OVER (ORDER BY C.NĂM)																								'TỔNG GIÁ TRỊ HĐTD NĂM TRƯỚC',
				ROUND(((SUM(C.CR_AMOUNT) - LAG(SUM(C.CR_AMOUNT), 1) OVER (ORDER BY C.NĂM)) / LAG(SUM(C.CR_AMOUNT), 1) OVER (ORDER BY C.NĂM)) * 100, 2)		'TĂNG TRƯỞNG HĐTD',
				SUM(C.COL_AMOUNT)																															'TỔNG GIÁ TRỊ TSBĐ',
				LAG(SUM(C.COL_AMOUNT), 1) OVER (ORDER BY C.NĂM)																								'TỔNG GIÁ TRỊ TSBĐ NĂM TRƯỚC',
				ROUND(((SUM(C.COL_AMOUNT) - LAG(SUM(C.COL_AMOUNT), 1) OVER (ORDER BY C.NĂM)) / LAG(SUM(C.COL_AMOUNT), 1) OVER (ORDER BY C.NĂM)) * 100, 2)	'TĂNG TRƯỞNG TSBĐ'

FROM			(
	SELECT		A.MA_ID,
				A.CR_CONTRACT_DATE,
				A.CR_AMOUNT,
				A.CR_CONTRACT_END_DATE,
				B.COL_ID,
				B.COL_TYPE_CODE,
				B.COL_AMOUNT,
				2021 'NĂM'
	FROM		CREDIT_CONTRACT AS A
	LEFT JOIN	COLLATERALS		AS B	ON A.MA_ID = B.MA_ID
	WHERE		A.CR_CONTRACT_DATE <= '2021-12-31' AND A.CR_CONTRACT_END_DATE > '2021-12-31'
	UNION ALL
	SELECT		A.MA_ID,
				A.CR_CONTRACT_DATE,
				A.CR_AMOUNT,
				A.CR_CONTRACT_END_DATE,
				B.COL_ID,
				B.COL_TYPE_CODE,
				B.COL_AMOUNT,
				2022 'NĂM'
	FROM		CREDIT_CONTRACT AS A
	LEFT JOIN	COLLATERALS		AS B	ON A.MA_ID = B.MA_ID
	WHERE		A.CR_CONTRACT_DATE <= '2022-12-31' AND A.CR_CONTRACT_END_DATE > '2022-12-31'
	UNION ALL
	SELECT		A.MA_ID,
				A.CR_CONTRACT_DATE,
				A.CR_AMOUNT,
				A.CR_CONTRACT_END_DATE,
				B.COL_ID,
				B.COL_TYPE_CODE,
				B.COL_AMOUNT,
				2023 'NĂM'
	FROM		CREDIT_CONTRACT AS A
	LEFT JOIN	COLLATERALS		AS B	ON A.MA_ID = B.MA_ID
	WHERE		A.CR_CONTRACT_DATE <= '2023-12-31' AND A.CR_CONTRACT_END_DATE > '2023-12-31'
	) AS C
GROUP BY		C.NĂM







